### ISSUE TITLE
Unable generate stall:model user

### ISSUE THREAD

**Issue by jbutkowski** [rails-stall/stall#2]
`rails generate stall:model user` fails on a fresh install.

```
/Users/jb/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.3/lib/active_record/dynamic_matchers.rb:21:in `method_missing': undefined method `devise' for User(Table doesn't exist):Class (NoMethodError)
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/stall-0.3.3/app/models/stall/models/user.rb:9:in `block in <module:User>'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/concern.rb:120:in `class_eval'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/concern.rb:120:in `append_features'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/stall-0.3.3/app/models/user.rb:2:in `include'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/stall-0.3.3/app/models/user.rb:2:in `<class:User>'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/stall-0.3.3/app/models/user.rb:1:in `<top (required)>'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:477:in `load'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:477:in `block in load_file'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:662:in `new_constants_in'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:476:in `load_file'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:375:in `block in require_or_load'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:358:in `require_or_load'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:511:in `load_missing_constant'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:203:in `const_missing'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/inflector/methods.rb:268:in `const_get'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/inflector/methods.rb:268:in `block in constantize'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/inflector/methods.rb:266:in `each'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/inflector/methods.rb:266:in `inject'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/inflector/methods.rb:266:in `constantize'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:583:in `get'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:614:in `constantize'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise.rb:313:in `get'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise/mapping.rb:81:in `to'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise/mapping.rb:76:in `modules'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise/mapping.rb:93:in `routes'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise/mapping.rb:160:in `default_used_route'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise/mapping.rb:70:in `initialize'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise.rb:343:in `new'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise.rb:343:in `add_mapping'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise/rails/routes.rb:241:in `block in devise_for'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise/rails/routes.rb:240:in `each'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/devise-4.3.0/lib/devise/rails/routes.rb:240:in `devise_for'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/stall-0.3.3/lib/stall/routes.rb:11:in `block in draw'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/stall-0.3.3/lib/stall/routes.rb:10:in `instance_eval'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/stall-0.3.3/lib/stall/routes.rb:10:in `draw'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/stall-0.3.3/lib/stall/rails/routing_mapper.rb:7:in `mount_stall'
	from /Users/jb/src/stall/config/routes.rb:2:in `block in <top (required)>'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/jb/src/stall/config/routes.rb:1:in `<top (required)>'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:287:in `load'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:287:in `load'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/initializable.rb:30:in `run'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/jb/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/jb/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/jb/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/jb/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/jb/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/jb/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/jb/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/jb/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/jb/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application.rb:352:in `initialize!'
	from /Users/jb/src/stall/config/environment.rb:5:in `<top (required)>'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/application.rb:328:in `require_environment!'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:157:in `require_application_and_environment!'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:60:in `generate'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/jb/.rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by vala** [comment]
We lately refactored to intergrate our admin panel ([para](/para-cms/para)) with `stall`, and I think we didn't update the install generator for a fresh install.

Please try using `rails g para:install` before any other `stall` generator
